from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Mapping


@dataclass(frozen=True)
class ChatAnswer:
    """A chat answer and the metadata collected by the Vizhi backend."""

    content: str
    input_tokens: int
    output_tokens: int
    total_tokens: int
    latency_ms: int
    model: str
    provider: str
    query_id: str
    agent_id: str
    response_id: str
    finish_reason: str
    raw: Mapping[str, Any] = field(repr=False)

    @property
    def answer(self) -> str:
        """Compatibility alias for the generated content."""
        return self.content

    @property
    def token(self) -> int:
        """Number of tokens generated by the model."""
        return self.output_tokens

    @property
    def token_queried(self) -> int:
        """Number of tokens sent to the model."""
        return self.input_tokens

    @property
    def time_taken(self) -> int:
        """Backend-reported request time in milliseconds."""
        return self.latency_ms
